class NavLocators:
    NAV_MENU_AUTO_ID = "menuBar"
    CUSTOMER_MANAGEMENT = "고객관리"
    INSURANCE_CLAIM = "보험청구"
    ELECTRONIC_SIGNATURE = "전자서명"
    FORM_PRINTING = "서식출력"
    SALES_MANAGEMENT = "매출관리"
    MEDICINE = "의약품"
    NARCOTICS = "마약류"
    RESERVATION_MANAGEMENT = "예약 관리"
    SETTINGS = "설정"
    SCREEN = "화면"
    CUSTOMER_SUPPORT = "고객지원"
    ADMIN = "관리자"
    DASHBOARD = "Dashboard"
    WAITING_STATUS_BOARD = "대기 현황판"
    RESERVATION_CALENDAR = "예약캘린더"